In [1]:
import pandas as pd

In [2]:
meta = pd.read_csv("metaDataForText.csv", index_col = 0)

In [3]:
meta.head()

articleId                      title              subTitle  \
0       @bookdb_782  사진으로 옮기기에도 아까운, 리치필드 국립공원  세상 어디에도 없는 호주 Top 10   
1     @kohwang56_81                  [시] 서러운 봄                   NaN   
2    @hannahajink_4                     무엇을 위해                무엇 때문에   
3  @bryceandjuli_88                         싫다                   NaN   
4   @mijeongpark_34                 Dubliner#7     #7. 내 친구의 집은 어디인가   

              datetime                 keywords  magazineId  
0  2016-09-27 11:47:07     ['여행', '호주', '국립공원']        8982  
1  2016-05-13 07:39:09    ['목련꽃', '아지랑이', '동행']       12081  
2  2015-11-20 14:28:07                       []           0  
3  2017-04-01 22:59:21       ['감정', '마음', '위로']       16315  
4  2018-04-10 01:55:42  ['유럽여행', '더블린', '아일랜드']       29363

In [4]:
meta = meta.fillna("")

In [68]:
titles = meta['title'] + " " + meta['subTitle']

In [89]:
titles

0             사진으로 옮기기에도 아까운 리치필드 국립공원 세상 어디에도 없는 호주 Top 10
1                                                  시 서러운 봄 
2                                             무엇을 위해 무엇 때문에
3                                                       싫다 
4                                 Dubliner7 7 내 친구의 집은 어디인가
5                                    지식기술이 가장 경쟁력 있는 자원이다  
6                                 유치권 심문기일 2007년 10월 8일 월요일
7                                             Rain 꼬꼬마의 글공간
8                                 출간제의 받았습니다 미안하지만 아직 학생입니다
9                                     동시빵가게 8 동시빵 맛보기도시 애벌레
10                                       같은 물건의 다른 삶 MD의 꽃점
11                            여의도 세계 불꽃축제 2007년 10월 13일 토요일
12                                      동시빵가게 6 동시빵 맛보기 펠리컨
13                           어줍잖게 힘들거면 힘들지마 그런 말을 하던 때가 있었다
14                                 여행 단상 1 6 나는 왜 떠나왔는가   2
15                                                       상 
16                                      

In [90]:
with open('titleSubs.pkl', 'wb') as t: 
    pickle.dump(titles, t)

In [6]:
import string

In [7]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [10]:
titles = titles.apply(lambda x : x.lower())

In [ ]:
titles = titles.apply(lambda x : "".join(c for c in x if c not in string.punctuation))

In [7]:
import re

In [54]:
nons = re.compile(r'[^가-힣a-zA-Z0-9\s]')

titles = titles.apply(lambda x : re.sub(nons, "", x))

In [70]:
titles

0             사진으로 옮기기에도 아까운 리치필드 국립공원 세상 어디에도 없는 호주 Top 10
1                                                  시 서러운 봄 
2                                             무엇을 위해 무엇 때문에
3                                                       싫다 
4                                 Dubliner7 7 내 친구의 집은 어디인가
5                                    지식기술이 가장 경쟁력 있는 자원이다  
6                                 유치권 심문기일 2007년 10월 8일 월요일
7                                             Rain 꼬꼬마의 글공간
8                                 출간제의 받았습니다 미안하지만 아직 학생입니다
9                                     동시빵가게 8 동시빵 맛보기도시 애벌레
10                                       같은 물건의 다른 삶 MD의 꽃점
11                            여의도 세계 불꽃축제 2007년 10월 13일 토요일
12                                      동시빵가게 6 동시빵 맛보기 펠리컨
13                           어줍잖게 힘들거면 힘들지마 그런 말을 하던 때가 있었다
14                                 여행 단상 1 6 나는 왜 떠나왔는가   2
15                                                       상 
16                                      

In [ ]:
help(re)

In [ ]:
titles[1]

In [ ]:
titles[7]

In [14]:
frequency = {}

for line in titles : 
    temp = line.strip().split()
    for item in temp : 
        if item not in frequency : 
            frequency[item] = 1
        frequency[item] += 1

In [15]:
frequencySorted = sorted(frequency.items(), key=lambda x : x[1], reverse=True)

In [ ]:
frequencySorted

In [ ]:
len(frequencySorted)

In [ ]:
sum([x[1] for x in frequencySorted[:30000]])

In [ ]:
sum(frequency.values())

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [71]:
tfidf = TfidfVectorizer(max_features=30000, analyzer='word', ngram_range=(1,2))

In [72]:
tfidf2 = TfidfVectorizer(max_features=60000, analyzer='word', ngram_range=(1,2))

In [83]:
tfidf3 = TfidfVectorizer(max_features=30000, analyzer='word')

In [73]:
tfidfMatrix = tfidf.fit_transform(titles)

In [74]:
tfidfMatrix2 = tfidf2.fit_transform(titles)

In [84]:
tfidfMatrix3 = tfidf3.fit_transform(titles)

In [15]:
len(tfidf.vocabulary_)

30000

In [91]:
with open('titleTfidfMatrix.pkl', 'wb') as f:
    pickle.dump(tfidfMatrix2, f)

In [75]:
coss = tfidfMatrix.dot(tfidfMatrix[0].transpose())

In [76]:
coss2 = tfidfMatrix2.dot(tfidfMatrix2[0].transpose())

In [85]:
coss3 = tfidfMatrix3.dot(tfidfMatrix3[0].transpose())

In [48]:
enumerate(coss2)

In [25]:
simm = coss.toarray()

In [77]:
simm60000 = [(i, j[0]) for i, j in enumerate(coss2.toarray())]

In [78]:
simm2 = [(i, j[0]) for i, j in enumerate(coss.toarray())]

In [86]:
simmUni = [(i, j[0]) for i, j in enumerate(coss3.toarray())]

In [79]:
simm3 = sorted(simm2, key = lambda x : x[1], reverse=True)

In [80]:
newSim = sorted(simm60000, key=lambda x : x[1], reverse=True)

In [87]:
uniSim = sorted(simmUni, key= lambda x : x[1], reverse=True)

In [32]:
simm3

[(0, 1.0),
 (530947, 0.7376991813306654),
 (98265, 0.6587553928943706),
 (435307, 0.6461511069373213),
 (416810, 0.6153878215554403),
 (517521, 0.5975543633222906),
 (480514, 0.5742466686997785),
 (39472, 0.5705128041012978),
 (567213, 0.5488413657529201),
 (4271, 0.5410868717235097),
 (496235, 0.5200294631573299),
 (515926, 0.5152721152290433),
 (538881, 0.49403954727667376),
 (456063, 0.4938216888360922),
 (246390, 0.4765461863238624),
 (418289, 0.46495234531193796),
 (514094, 0.4592444794797648),
 (249119, 0.45171201129174143),
 (548308, 0.4476099046159281),
 (548236, 0.4451558395922038),
 (548287, 0.43552847713617193),
 (148190, 0.43232537266844506),
 (557935, 0.3982670054960289),
 (562055, 0.3906817580165617),
 (75486, 0.38868071870575926),
 (161765, 0.3880946494692859),
 (378213, 0.3861891824971031),
 (30566, 0.3786140105973911),
 (243458, 0.37534135580998673),
 (569547, 0.3749997335119991),
 (105105, 0.36991010334329),
 (609798, 0.36945063278609547),
 (445144, 0.3693935899447945

In [26]:
for i, j in enumerate(simm):
    print(i, j)
    break

0 [1.]


In [14]:
tfidf.get_params()

{'analyzer': 'word',
 'binary': False,
 'decode_error': 'strict',
 'dtype': numpy.float64,
 'encoding': 'utf-8',
 'input': 'content',
 'lowercase': True,
 'max_df': 1.0,
 'max_features': 30000,
 'min_df': 1,
 'ngram_range': (1, 1),
 'norm': 'l2',
 'preprocessor': None,
 'smooth_idf': True,
 'stop_words': None,
 'strip_accents': None,
 'sublinear_tf': False,
 'token_pattern': '(?u)\\b\\w\\w+\\b',
 'tokenizer': None,
 'use_idf': True,
 'vocabulary': None}

In [ ]:
tfidfMatrix

In [20]:
from scipy.sparse.linalg import svds

In [25]:
reduced = svds(tfidfMatrix, k=500, return_singular_vectors='u')

In [19]:
tfidfMatrix[0].toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

In [36]:
import pickle

In [38]:
with open('titleTfIdf.pkl', 'rb') as f:
    tfidfUniMatrix = pickle.load(f)

In [39]:
coss2 = tfidfUniMatrix.dot(tfidfUniMatrix[0].transpose()).toarray()

In [40]:
simmmm = [(x, y) for x, y in enumerate(coss2)]

In [65]:
with open('titleTfIdf.pkl', 'wb') as f :
    pickle.dump(tfidfMatrix, f)

In [38]:
simm = []
count = 0
for i in range(tfidfMatrix.shape[0]) : 
    coss = tfidfMatrix[0].dot(tfidfMatrix[i].transpose())
    coss = coss.toarray()[0][0]
    simm.append((count, coss))

In [42]:
simm2 = []
for count, cos in enumerate(simm):
    simm2.append((count + 1, cos[1]))
    

In [41]:
sortedSimm = sorted(simmmm, key=lambda x : x[1], reverse=True)

In [81]:
titles[[x for x, y in newSim[:50]]]

0             사진으로 옮기기에도 아까운 리치필드 국립공원 세상 어디에도 없는 호주 Top 10
530947         세상에서 가장 큰 모래섬 프레이저 아일랜드 세상 어디에도 없는 호주 Top 10
98265      세상 어디에도 없는 독특한 맛 캥거루고기를 아시나요 세상 어디에도 없는 호주 Top10
435307    살아온 날보다 살아갈 날이 많은 나의 최선의 선택 호주 프롤로그 세상 어디에도 없는...
480514                                     착한 남자 세상 어디에도 없는
517521                  반듯하게 계획된 도시 캔버라 세상 어디에도 없는 호주 Top10
4271                             화분 적당함이란 세상 어디에도 없는 것일지 몰라
416810                            세상 어디에도 없는 절규남자 후지산 여행기 셋
496235                       세상 어디에도 없는 갑 Korean Gapjil Air
39472      세계 최대의 고래 축제 허비 베이 고래 관찰 투어 세상 어디에도 없는 호주 Top 10
538881                                      마츠코 어디에도 없는 사모님
567213     환상적인 일몰 그리고 자유 헨티 모래언덕의 모래썰매 세상 어디에도 없는 호주 Top10
514094     에덴 이 세상 어디에도 없는 그래서 슬픈  구가의 서 my eden에 대한 짧은 에세이
456063                         가자 비밀의 땅으로 세상 어디에도 없는 국내여행지 
491300                               리우데자네이루의 TOP 10 VIEWS 
583514                                     TOP 10 한물간 음악장르 
515926       세상 어디에도 없는 길 아이스필드 파크 어웨이 두

In [82]:
titles[[x for x, y in simm3[:50]]]

0             사진으로 옮기기에도 아까운 리치필드 국립공원 세상 어디에도 없는 호주 Top 10
530947         세상에서 가장 큰 모래섬 프레이저 아일랜드 세상 어디에도 없는 호주 Top 10
98265      세상 어디에도 없는 독특한 맛 캥거루고기를 아시나요 세상 어디에도 없는 호주 Top10
435307    살아온 날보다 살아갈 날이 많은 나의 최선의 선택 호주 프롤로그 세상 어디에도 없는...
416810                            세상 어디에도 없는 절규남자 후지산 여행기 셋
480514                                     착한 남자 세상 어디에도 없는
517521                  반듯하게 계획된 도시 캔버라 세상 어디에도 없는 호주 Top10
39472      세계 최대의 고래 축제 허비 베이 고래 관찰 투어 세상 어디에도 없는 호주 Top 10
4271                             화분 적당함이란 세상 어디에도 없는 것일지 몰라
496235                       세상 어디에도 없는 갑 Korean Gapjil Air
515926       세상 어디에도 없는 길 아이스필드 파크 어웨이 두근두근 57세 홀로 캐나다재스퍼 2
567213     환상적인 일몰 그리고 자유 헨티 모래언덕의 모래썰매 세상 어디에도 없는 호주 Top10
538881                                      마츠코 어디에도 없는 사모님
456063                         가자 비밀의 땅으로 세상 어디에도 없는 국내여행지 
418289       세상 어디에도 없는 곳 Neverwhere 때로 모험은 아주 가까운 곳에서 시작된다
514094     에덴 이 세상 어디에도 없는 그래서 슬픈  구가의 서 my eden에 대한 짧은 에세이
246390    죽기 전에 꼭 한번 해봐야 할바이런 베이 스카이다이빙 

In [88]:
titles[[x for x, y in uniSim[:50]]]

0             사진으로 옮기기에도 아까운 리치필드 국립공원 세상 어디에도 없는 호주 Top 10
530947         세상에서 가장 큰 모래섬 프레이저 아일랜드 세상 어디에도 없는 호주 Top 10
98265      세상 어디에도 없는 독특한 맛 캥거루고기를 아시나요 세상 어디에도 없는 호주 Top10
435307    살아온 날보다 살아갈 날이 많은 나의 최선의 선택 호주 프롤로그 세상 어디에도 없는...
416810                            세상 어디에도 없는 절규남자 후지산 여행기 셋
325789                                  세계 최고의 국립공원 TOP 10 
538881                                      마츠코 어디에도 없는 사모님
517521                  반듯하게 계획된 도시 캔버라 세상 어디에도 없는 호주 Top10
491300                               리우데자네이루의 TOP 10 VIEWS 
583514                                     TOP 10 한물간 음악장르 
169432                                    어디에도 실릴 수 없는 이야기 
414089                                               아까운 것 
480514                                     착한 남자 세상 어디에도 없는
315435    실베스터 스탤론 TOP 10 영화 TOP 10  Sylvester Stallone ...
315440    브루스 윌리스 TOP 10 영화 TOP 10  Bruce Willis Perform...
39472      세계 최대의 고래 축제 허비 베이 고래 관찰 투어 세상 어디에도 없는 호주 Top 10
236631                                  

In [27]:
tfidfMatrix.shape

(643104, 30000)

In [32]:
gdx = tfidfMatrix[0].dot(tfidfMatrix[0].transpose())

In [37]:
gdx.toarray()

array([[1.]])

In [ ]:
reduced[0].shape

In [ ]:
reduced[2].shape

In [70]:
import numpy as np

In [ ]:
np.dot(reduced[0][0], reduced[0][1])

In [ ]:
len(reduced[0][0])

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
cosine_similarity(reduced[0][0], reduced[0][1])

In [ ]:
from sklearn.preprocessing import normalize

In [ ]:
normz = normalize(reduced[0])

In [ ]:
similarity = []

In [ ]:
count = 1
for t in normz[1:]:
    coss = np.dot(normz[0], t)
    similarity.append((count, coss))
    count +=1

In [ ]:
ss = sorted(similarity, key = lambda x : abs(x[1]), reverse=True)

In [ ]:
ss

In [48]:
titles[[0, 252413, 269661, 57840]]

0            사진으로 옮기기에도 아까운 리치필드 국립공원 세상 어디에도 없는 호주 top 10
252413    피터 드러커로 경영과 세상 읽기10 druker weekly 10 정상적인 사회와 경영
269661                                10 뻐꾸기 연필에 닿는 세상 375
57840                           그림을 통한 아들의 세상 10 차가운 습기 축제
dtype: object

In [ ]:
tfidfMatrix

In [19]:
sim = tfidfMatrix.dot(tfidfMatrix.transpose())

MemoryError: 

In [75]:
tfidfMatrix[0].dot(tfidfMatrix[252413].transpose()).toarray()[0]

array([0.13076352])

In [77]:
cosscolumn = tfidfMatrix.dot(tfidfMatrix[0].transpose())

In [82]:
sortedColumn = sorted(enumerate(cosscolumn.toarray()), key = lambda x : x[1][0], reverse=True)

In [81]:
cosscolumn.toarray()

array([[1.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [83]:
sortedColumn

[(0, array([1.])),
 (530947, array([0.61326538])),
 (98265, array([0.51951345])),
 (435307, array([0.4973961])),
 (416810, array([0.46997853])),
 (325789, array([0.45583356])),
 (538881, array([0.45505246])),
 (517521, array([0.420168])),
 (491300, array([0.41965265])),
 (583514, array([0.41965265])),
 (169432, array([0.41944708])),
 (414089, array([0.41291157])),
 (480514, array([0.41099931])),
 (315435, array([0.40751854])),
 (315440, array([0.40751854])),
 (39472, array([0.39889862])),
 (236631, array([0.39077005])),
 (488482, array([0.39077005])),
 (567213, array([0.37859095])),
 (31893, array([0.37331334])),
 (54868, array([0.37331334])),
 (423737, array([0.37331334])),
 (538964, array([0.37331334])),
 (595635, array([0.37331334])),
 (636654, array([0.37331334])),
 (4271, array([0.37060604])),
 (609798, array([0.36702301])),
 (445144, array([0.36696656])),
 (445172, array([0.36671705])),
 (445265, array([0.36663632])),
 (78779, array([0.36447948])),
 (261694, array([0.36253916])),

In [15]:
from sklearn.preprocessing import normalize

In [18]:
normalize([[1,2,3],[3,2,4]])

array([[0.26726124, 0.53452248, 0.80178373],
       [0.55708601, 0.37139068, 0.74278135]])